### PR TITLE
Make finite samplers report the number of samples they contain

### PR DESCRIPTION
**Pull request by orbitfold**
I can imagine it being useful (e.g. for resource allocation purposes)

### CODE REVIEW

**Comment by jlakhlili** [comment]
@orbitfold We had already `n_samples` as attribute. Why a new property?

**Comment by orbitfold** [comment]
> @orbitfold We had already `n_samples` as attribute. Why a new property?

Where? It has to be something all finite samplers provide in the same way. Right now some samplers don't do it at all and some call it differently. So it is not part of the interface for Samplers.

**Comment by orbitfold** [comment]
Also @jlakhlili can you add in qmc.py and pce.py and maybe the stochastic collocation one, in the docstring of n_samples, an explanation for how the number of samples are calculated

**Comment by jlakhlili** [comment]
> > @orbitfold We had already `n_samples` as attribute. Why a new property?
> 
> Where? It has to be something all finite samplers provide in the same way. Right now some samplers don't do it at all and some call it differently. So it is not part of the interface for Samplers.

Actually we had it in PCE and QMC, in SC it called ` _number_of_samples`.
 But, it's right, we should have it in all Samplers with unique name.
My question, why you want to use function instead of simple attribute?

**Comment by jlakhlili** [comment]
> Also @jlakhlili can you add in qmc.py and pce.py and maybe the stochastic collocation one, in the docstring of n_samples, an explanation for how the number of samples are calculated
 Sure.

**Comment by orbitfold** [comment]
> > > @orbitfold We had already `n_samples` as attribute. Why a new property?
> > 
> > 
> > Where? It has to be something all finite samplers provide in the same way. Right now some samplers don't do it at all and some call it differently. So it is not part of the interface for Samplers.
> 
> Actually we had it in PCE and QMC, in SC it called ` _number_of_samples`.
> But, it's right, we should have it in all Samplers with unique name.
> My question, why you want to use function instead of simple attribute?

Why not? We can convert it to an attribute by adding the `@property` decorator to the function. Also if it is a function we can force classes that inherit from Base Sampler to implement it. If it is an attribute you can't do it. Also, for example in the Sweep sampler you have to do some math to calculate the size.

**Comment by jlakhlili** [comment]
> > Also @jlakhlili can you add in qmc.py and pce.py and maybe the stochastic collocation one, in the docstring of n_samples, an explanation for how the number of samples are calculated
> > Sure.

@orbitfold please check docstring if it's clear...

**Comment by orbitfold** [comment]
Looks good to me.

**Pull request merged**
