### PR TITLE
Check order sc

### PR DESCRIPTION
**Pull request by wedeling**
Made it possible to give different polynomial orders for different uncertain variables to create anisotropic grids:

```python
my_sampler = uq.sampling.SCSampler(vary=vary, polynomial_order=[1,4])
```

Only works for stochastic collocation. Does not work for sparse grids.

### CODE REVIEW

**Comment by orbitfold** [comment]
Please solve PEP8 issues. The easiest way is to run py.test --pep8 easyvvuq/ in your root EasyVVUQ dir and then fix any errors it reports.

**Comment by orbitfold** [comment]
Also we need people to start writing tests with each PR.

**Comment by wedeling** [comment]
PEP 8 issues are fixed now

**Comment by orbitfold** [comment]
So do you see any easy ways to test this new functionality? ;) I'd help to write the tests if needed.

**Comment by wedeling** [comment]
@orbitfold I've added a test for this in `tests/test_anisotropic_order.py`. Is this what you meant? It's just a normal SC campaign with different polynomial orders for the two uncertain parameters

**Comment by wedeling** [comment]
I'll fix the pep8 stuff btw

**Pull request merged**
