### PR TITLE
Issue401: Inconsistent sampled values when mixing continuous and discrete distributions

### LINKED ISSUE #401: Inconsistent sampled values when mixing continuous and discrete distributions
# Bug Report

## Description:
I encountered a scenario within my use case where I need to sample both floating-point and integer numbers for my model. In the process of defining a `params` dictionary, I've noticed an inconsistency when combining distributions of type `cp.Normal` and `cp.DiscreteUniform` within the `vary` dictionary. Specifically, when utilizing the SC sampler, integer values are being sampled correctly, but they are incorrectly identified as being of type `class <float>`. This misidentification triggers constraints related to integer types within the `params` dictionary.

Furthermore, when employing PCE and MC samplers, I've observed a behavior where the samplers inconsistently sample both float and integer values. This inconsistency persists despite using the `cp.DiscreteUniform` distribution class (returned values like `18.996` or `24.52345`). The reported values, despite being constrained to integers, are still indicated as `class <float>`. This behavior is inconsistent with the expected behavior of the distribution.

The expectation is that when using `cp.DiscreteUniform` distribution, integer values should be sampled consistently and correctly identified as integer types, not misclassified as floating-point types.

### First case
1. Prepare model provided in **Additional context** section.
2. Setup params dictionary:
```python3
params = {
    "steamT": {"type": "integer", "default": 600},
    "steamP": {"type": "integer", "default": 30},
    "liquidT": {"type": "float", "default": 10},
    "liquidP": {"type": "float", "default": 20},
    "liquidV": {"type": "integer", "default": 2},
    "tankV": {"type": "integer", "default": 15},
}
```
3. Create a sample `vary` dictionary with example data like this:
```python3
vary = {
    "steamT": cp.DiscreteUniform(100, 600),
    "steamP": cp.DiscreteUniform(5, 30),
    "liquidT": cp.Normal(15, 3),
    "liquidP": cp.Normal(10, 2),
    "liquidV": cp.DiscreteUniform(1, 2),
    # "tankV": cp.Normal(15, 2) # Tank V is const
}
```
4. Set actions, sampler and execute:
```python3
encoder = uq.encoders.GenericEncoder(
    template_fname="config.template", delimiter="$", target_filename="input.json"
)
decoder = uq.decoders.JSONDecoder(
    target_filename="output.json", output_columns=["finalT", "finalP"]
)
execute = ExecuteLocal(f"python3 {os.getcwd()}/steam-water-equilibrium.py input.json")
actions = Actions(CreateRunDirectory("/tmp"), Encode(encoder), execute, Decode(decoder))
campaign = uq.Campaign(name="steam-water", params=params, actions=actions)

### Sampler set
campaign.set_sampler(uq.sampling.SCSampler(vary=vary, polynomial_order=1))
with QCGPJPool(
    template=EasyVVUQParallelTemplate(),
    template_params={
        "venv": r"/home/<username>/.pyenv/versions/3.10.7/envs/steam-water"
    },
) as qcgpj:
    campaign.execute(pool=qcgpj).collate()
```
5. Observe error:
```python3
>>> RuntimeError: Error when verifying the following new run:
{'steamT': 225.0, 'steamP': 11.0, 'liquidT': 12.0, 'liquidP': 8.0, 'liquidV': 1.0, 'tankV': 15}
Identified errors were:
{'liquidV': ['must be of integer type'], 'steamP': ['must be of integer type'], 'steamT': ['must be of integer type']}
```
As you can see, the values are correctly sampled as integers, but returned as `class<float>`. What's interesting is that when setting `polynomial_order=1`, some parameters, despite being declared as `cp.Normal`, were also sampled as integers (still returned as `class<float>`) When setting higher `polynomial_order`, values with distribution set as `cp.Normal` or other continuous distribution type are more likely to be floating point numbers like `18.2334`.

### Second case
1. Repeat first case up to `set_sampler()` step.
2. Set actions, sampler and execute:
```python3
### Sampler set
campaign.set_sampler(uq.sampling.PCESampler(vary=vary, polynomial_order=1))
with QCGPJPool(
    template=EasyVVUQParallelTemplate(),
    template_params={
        "venv": r"/home/<username>/.pyenv/versions/3.10.7/envs/steam-water"
    },
) as qcgpj:
    campaign.execute(pool=qcgpj).collate()
``` 
3. Observe error:
```python3
>>> RuntimeError: Error when verifying the following new run:
{'steamT': 205.3738767467413, 'steamP': 10.000279551072868, 'liquidT': 12.0, 'liquidP': 8.0, 'liquidV': 0.9999999999999998, 'tankV': 15}
Identified errors were:
{'liquidV': ['must be of integer type'], 'steamP': ['must be of integer type'], 'steamT': ['must be of integer type']}
```

As you can see here the values were once again returned as `class<float>` but this time they were not integers? `steamT` is an integer class, but was sampled as `205.3738767467413`, the same goes for `steamP` variable and `liquidV`. The only  varaibles sampled as integers were ones declared as `float`.

## Environment:
Operating System: [e.g., `Ubuntu 22.04 `- WSL1]
Python: `3.10.7`
EasyVVUQ: currently newest on Pypi, `1.2`.
Chaospy version: `4.3.2`
Venv manager - `pyenv`

## Additional Context:
Model that I'm using:
```python3
#!/usr/bin/env python3

# These code contains material and example problems in thermodynamics.
# This code was used from https://kyleniemeyer.github.io/computational-thermo/
# under Creative Commons Attribution 4.0 International License.

# Steam equilibrating with liquid water
######################################
# Accident scenario: steam leaks into a rigid, insulated tank that is partially filled with water.
# The steam and liquid water are not initially at thermal equilibrium, though they are at the same pressure.
# The steam is at temperature 600 C and pressure 20 MPa.
# The liquid water is initially at 40 C and pressure 20 MPa.
# The total volume of the tank is 10 m^3
# And the volume of the liquid water initially in the tank is 1 m^3.

# Eventually, the contents of the tank reach a uniform temperature and pressure.
# The tank is well-insulated and rigid.

# Problem: Determine the final temperature and pressure of the water in the tank.

import dataclasses
import json
import sys

import numpy as np
import cantera as ct
from pint import UnitRegistry


@dataclasses.dataclass
class Config:
    steamT: float  # Initial steam temperature (degC)
    steamP: float  # Initial steam pressure (MPa)
    liquidT: float  # Initial liquid temperature (degC)
    liquidP: float  # Initial liquid pressure (MPa)
    liquidV: float  # Liquid volume initially in the tank (m^3)
    tankV: float  # Volume of the tank (m^3)

    @staticmethod
    def decode(cfg):
        return Config(**cfg)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("ERROR: Config file not provided")
        sys.exit(1)
    with open(sys.argv[1]) as fh:
        config = json.load(fh, object_hook=Config.decode)

    # Setup UnitRegistry to handle unit conversion and manipulation
    ureg = UnitRegistry()
    Q_ = ureg.Quantity

    # Setup Cantera environment providing steam and liquid
    steam = ct.Water()
    temp_steam1 = Q_(config.steamT, "degC")
    pres1 = Q_(config.steamP, "MPa")
    steam.TP = temp_steam1.to("K").magnitude, pres1.to("Pa").magnitude
    steam()

    liquid = ct.Water()
    temp_liquid1 = Q_(config.liquidT, "degC")
    pres_liquid1 = Q_(config.liquidP, "MPa")
    liquid.TP = temp_liquid1.to("K").magnitude, pres_liquid1.to("Pa").magnitude
    liquid()

    # "Calculate the mass of liquid water in the tank, and then determine the volume and mass of steam"
    vol_tank = Q_(config.tankV, "meter^3")
    vol_liquid1 = Q_(config.liquidV, "meter^3")
    mass_liquid1 = vol_liquid1 / Q_(liquid.v, "m^3/kg")
    print(f"Mass of liquid at state 1: {mass_liquid1: .2f}")
    vol_steam1 = vol_tank - vol_liquid1
    mass_steam1 = vol_steam1 / Q_(steam.v, "m^3/kg")
    print(f"Mass of steam at state 1: {mass_steam1: .2f}")
    mass_1 = mass_liquid1 + mass_steam1
    print(f"Total mass of system: {mass_1: .2f}")

    mass_2 = mass_1
    spec_vol2 = vol_tank / mass_2
    print(f"Specific volume of state 2: {spec_vol2: .2e}")
    int_energy2 = (Q_(liquid.u, "J/kg") * mass_liquid1 + Q_(steam.u, "J/kg") * mass_steam1) / mass_2
    int_energy2.ito("kilojoule/kg")
    print(f"Internal energy of state 2: {int_energy2: .2f}")
    water_equilibrium = ct.Water()
    water_equilibrium.UV = int_energy2.to("J/kg").magnitude, spec_vol2.to("m^3/kg").magnitude
    water_equilibrium()

    # "At equilibrium, the tank contains a mixture of saturated liquid and vapor, with temperature and pressure"
    final_temperature = Q_(water_equilibrium.T, "K")
    final_pressure = Q_(water_equilibrium.P, "Pa")

    print(f"Final temperature: {final_temperature: .2f}")
    print(f"Final pressure: {final_pressure.to(ureg.MPa): .2f}")

    with open("output.json", "w+") as fh:
        content = json.dumps({"finalT": final_temperature.magnitude, "finalP": final_pressure.to(ureg.MPa).magnitude})
        fh.write(content)
```

My template file `config.template`:
```json
{
  "steamT": $steamT,
  "steamP": $steamP,
  "liquidT": $liquidT,
  "liquidP": $liquidP,
  "liquidV": $liquidV,
  "tankV": $tankV
}

```

### Reproducibility:
- The bug happens consistently.

### Related Issues:
If you found any similar or related issues on the repository, provide links here.

### PR DESCRIPTION
**Pull request by wedeling**
Fix for Issue  https://github.com/UCL-CCS/EasyVVUQ/issues/401

I changed the SC and PCE samplers such that when mixing continuous and discrete inputs, the inputs files contain float/integer values respectively. This is done by modifications of the `__next__` subroutines of both samplers.

For the PCE sampler I changed the `rule` such that only for the `cp.DiscreteUniform` inputs,  the quadrature rule is set to `"discrete"` instead of the standard Gaussian quad rule `"G"`. This was already done for the SC sampler. This must be done for `DiscreteUniform` inputs, otherswise e.g. `cp.DiscretUniform(1,2)` can lead to non-integer values such as 1.1, when fed to the `cp.generate_quadrature` method. 

`tests/test_mix_continuous_discrete.py` is the corresponding test for both samplers.

### CODE REVIEW

**Review by DavidPCoster — APPROVED** [review]

**Review by djgroen — APPROVED** [review]
Looks all good and especially essential to me.

**Comment by wedeling** [comment]
> Looks all good and especially essential to me.

@djgroen the readthedocs test failed due to missing configuration file. Will I mess up the readthedocs page if I merge this into `dev`?

**Comment by djgroen** [comment]
@wedeling We did not have such a file in previous versions, and readthedocs built fine at the time. So perhaps something updated on the readthedocs platform that broke the Build between our last commit and the current one?

A broken readthedocs build is not critical though in my experience: the old documentation will remain online while we still try to fix the new build.

So possibly the best bet is to merge this and then fix the build?

**Comment by wedeling** [comment]
> @wedeling We did not have such a file in previous versions, and readthedocs built fine at the time. So perhaps something updated on the readthedocs platform that broke the Build between our last commit and the current one?
> 
> A broken readthedocs build is not critical though in my experience: the old documentation will remain online while we still try to fix the new build.
> 
> So possibly the best bet is to merge this and then fix the build?

OK I merged it

**Pull request merged**
