### PR TITLE
Sensitivity analysis with correlated inputs

### PR DESCRIPTION
**Pull request by goghino**
The code contains method to perform sensitivity analysis of models with correlated inputs. The new SA is supported only by the PCE method. Changes include:

- Integration of Rosenblatt and Cholesky transformation to PCE (pce.py) implemented in a separate module (transformations.py)
- Computation of the derivative-based sensitivity index from the PCE (pce_analysis.py)
- Implementation of finite difference approximation of the derivative-based index (fd.py, fd_analysis.py)

The new code is accompanied by a publication elaborating on the method, and a set of Jupyter notebooks demonstrating the functionality (at the moment located in external repository).

Running the test suite results in some errors, but I think they do not originate from my updates. Please verify. @djgroen 
````
======================================== short test summary info =========================================
FAILED tests/test_SSC.py::test_adapt_locally - assert False
FAILED tests/test_mc_analysis_results.py::test_describe - AssertionError: assert {'10%': 0.081...20347433, ...} == {'mean': 0.46...4945020531205}
FAILED tests/test_vector.py::test_gauss_vector_pce - TypeError: len() of unsized object
ERROR tests/test_campaign.py::test_string - FileNotFoundError: [Errno 2] No such file or directory: '/Users/usi/switchdrive/Institution/usi/PhD/p...
ERROR tests/test_campaign.py::test_get_active_app - FileNotFoundError: [Errno 2] No such file or directory: '/Users/usi/switchdrive/Institution/usi/PhD/p...
ERROR tests/test_campaign.py::test_add_external_runs - FileNotFoundError: [Errno 2] No such file or directory: '/Users/usi/switchdrive/Institution/usi/PhD/p...
============== 3 failed, 143 passed, 5 skipped, 36 warnings, 3 errors in 257.08s (0:04:17) ===============```

### CODE REVIEW

**Comment by djgroen** [comment]
Hi all. This is a big pull request that needs wide scrutiny in my opinion. I do think the feature could find very widespread uptake, so I am in support of it. However, the code needs wide scrutiny :).

**Comment by orbitfold** [comment]
Where are the tests for this new functionality?

**Comment by DavidPCoster** [comment]
In order to understand a bit more about these changes, it would be good to have access to "The new code is accompanied by a publication elaborating on the method, and a set of Jupyter notebooks demonstrating the functionality (at the moment located in external repository)."

I might have missed where these were referenced, but could you make it easier to find them?

**Comment by djgroen** [comment]
@goghino Do you have any time to look into this perhaps?

**Comment by goghino** [comment]
@DavidPCoster I have added the jupyter notebooks to `tutorials/correlated`, there are two of them `coffe_cup-pce.ipynb` and `coffe_cup-fd.ipynb`. Regarding the publication, please find attached the  preprint
[SApaper_submission.pdf](https://github.com/UCL-CCS/EasyVVUQ/files/11530503/SApaper_submission.pdf)

**Comment by goghino** [comment]
Added tests for the new functionality:
 create mode 100644 tests/test_fd_analysis.py
 create mode 100644 tests/test_fd_dep_analysis.py
 create mode 100644 tests/test_pce_der_analysis.py
 create mode 100644 tests/test_pce_der_dep_analysis.py

**Comment by goghino** [comment]
Is there anything else I can do for this pull request? @djgroen @DavidPCoster @wedeling

**Review by DavidPCoster — APPROVED** [review]
I haven't examined every line of code but I am happy to see this brought in now.  

I propose first bringing it in as a new branch within the repository, and then if all of the standard tests pass, seeing it merged with dev.

@djgroen @orbitfold @wedeling -- what do you think?

**Review by DavidPCoster — CHANGES_REQUESTED** [review]
After I enabled testing (didn't know I could do that), some tests are failing.  These failures need to be addressed before merging.

**Comment by goghino** [comment]
I see, I am using some recent python syntax not supported in older versions, that's why "build (3.7)" fails. I will try to downgrade my code to be compatible with old python versions.

@DavidPCoster can I run the tests you launched myself as well? Because I think I will not get it all fixed on my first go.

Edit: Conda is not officially supporting 3.7 ("Conda supports Python 3.8, 3.9, 3.10, and 3.11.")

**Comment by DavidPCoster** [comment]
I don’t know — I found a button to enable test runs, but that might not be available to everybody ...

**Comment by goghino** [comment]
I am not able to create environment with python 3.7. I can set up only environment with 3.8 and newer. But with python=3.8.16 most of the tests pass

============ 24 failed, 111 passed, 5 skipped, 1090 warnings, 29 errors in 131.81s (0:02:11) =============

The errors and failures are related to some missing files, e.g.
ERROR test_campaign.py::test_get_active_app - FileNotFoundError: [Errno 2] No such file or directory: '...
/opt/homebrew/anaconda3/envs/USI_test_p38/lib/python3.8/subprocess.py:1704: FileNotFoundError

can we skip python 3.7 for the moment?

**Comment by DavidPCoster** [comment]
Well, security updates for 3.7 

Ends in 3 weeks and 6 days 
(27 Jun 2023)

So I think this should be OK.  @djgroen , @orbitfold , @wedeling -- what do you think?  If so, how do we disable the 3.7 tests?

**Pull request merged**
