### PR TITLE
speed up the creation of samples (in one case by > 500 times)

### PR DESCRIPTION
**Pull request by DavidPCoster**
@jlakhlili -- this speeds up the creation of samples by more than a factor of 500 in one test case (1024 samples, 100 points, 4 QOIs)

### CODE REVIEW

**Comment by jlakhlili** [comment]
Related issue: #231.

**Comment by orbitfold** [comment]
Is this still a work in progress or ready to be merged? Since it's marked as draft I am assuming there is still work to be done

**Comment by DavidPCoster** [comment]
Still a work in progress ...

**Comment by DavidPCoster** [comment]
I think we are now ready to merge.  The speedup for the analysis phase is of order 50, and for some of my cases, this was the most time consuming phase in my runs ...

**Pull request merged**
