### PR TITLE
Fix ndarray qois in pce_analysis

### PR DESCRIPTION
**Pull request by bartoszbosak**
There was a problem with `_describe` method in `pce_analysis` - it returned simple scalar values for percentiles, which was not properly handled outside, where `ndarray` is required.  This change seems to solve this problem and hopefully does not have a negative impact elsewhere.

### CODE REVIEW

**Review by djgroen — APPROVED** [review]
This passes all tests and looks good to me. David, do you agree?

**Comment by djgroen** [comment]
I've rerouted this ticket from David to Wouter. @bartoszbosak I just wanted to check: you still would like to have this merged into master, right?

**Comment by bartoszbosak** [comment]
> I've rerouted this ticket from David to Wouter. @bartoszbosak I just wanted to check: you still would like to have this merged into master, right?

Hi @djgroen, yes it would be nice to have it merged. I think that my proposition doesn't brake anything, but please double check :)

**Review by DavidPCoster — APPROVED** [review]
Looks OK to me.

**Comment by DavidPCoster** [comment]
@wedeling -- this seems to be waiting for your approval ...

**Comment by bartoszbosak** [comment]
Hi @wedeling, could you check this PR if it can be merged? Thanks in advance.

**Review by wedeling — COMMENTED** [review]
ok

**Pull request merged**
