### PR TITLE
Fix the draw_samples bug

### PR DESCRIPTION
**Pull request by orbitfold**
There is a bug in draw_samples where if num_samples is a float that is not exactly an integer it will enter an infinite loop. Which is why using >= and <= is preferable to ==.

### CODE REVIEW

**Comment by orbitfold** [comment]
But this somehow broke your tests @wedeling ?

**Comment by wedeling** [comment]
> But this somehow broke your tests @wedeling ?

It seems like the SC sampler only samples the code 1 time now

**Comment by wedeling** [comment]
@orbitfold It does indeed only sample the code once. For this test to work, I now need to manually specify the number of samples that have to be run: (line 83 of `test/sc/sparse_sc_test.py`)
```python
# Will draw all (of the finite set of samples)
my_campaign.draw_samples(num_samples=my_sampler._number_of_samples)
```

**Comment by orbitfold** [comment]
I really don't understand why would this change cause that behaviour?

**Comment by orbitfold** [comment]
Oh! I get it.

**Pull request merged**
