### PR TITLE
Test and refactor the similarity validation classes

### PR DESCRIPTION
**Pull request by orbitfold**

### CODE REVIEW

**Review by jlakhlili — APPROVED** [review]

**Comment by orbitfold** [comment]
It is still not tested properly so can't be merged. All the validation distances need to be tested for correctness with known values. @jlakhlili Also the docstrings need to be filled with exact details for how those functions work or references to wikipedia or papers.

**Comment by orbitfold** [comment]
Also a module docstring must be added following the NumPy conventions: https://numpydoc.readthedocs.io/en/latest/format.html#documenting-modules

**Comment by jlakhlili** [comment]
@orbitfold I added docstring and tests to `ValidationSimilaries` functions. But, I put `ValidationCompatiblity` aside, It needs some rework. Tutorial is also updated. I think, now it's ready to merge.

**Review by jlakhlili — APPROVED** [review]
- Hellinger distance can be comapred with Analytical function. 
- For JSD and Wasserstein, we can just ceck the ranges.

**Pull request merged**
