### PR TITLE
Update python-package.yml

### PR DESCRIPTION
**Pull request by djgroen**
Modified python-package to not rely on Py3.7 and instead test 3.10 and 3.11.

### CODE REVIEW

**Comment by djgroen** [comment]
Hi all. This is my attempt to revise the actions tests to use newer Python versions. It may well be that a variety of tests fail in the first instance. I will try to fix them where I can, but may rely on support where I get stuck :).

**Review by DavidPCoster — APPROVED** [review]
Looks good to me -- but I am not an expert on setting up the CI options.

**Review by DavidPCoster — APPROVED** [review]
Looks good to me -- but I am not an expert on setting up the CI options.

**Comment by djgroen** [comment]
@wedeling @orbitfold Could you please quickly check and approve this pull request? We need the EasyVVUQ build to be working again for the release, especially because we'd like to merge in other changes as well! :)

**Review by orbitfold — APPROVED** [review]
Looks fine to me

**Comment by djgroen** [comment]
Hi all. Two required tests seem to be utterly hanging, but I will merge this into master now so that other pull requests can also be checked. 

May have to look into the LGTM / travis-ci issues as well though :/.

**Pull request merged**
