### PR TITLE
Random sampler analysis class

### PR DESCRIPTION
**Pull request by wedeling**
Made the computation of the confidence intervals more efficient, by vectorizing the for loop over the number of bootstrap samples.

### CODE REVIEW

**Review by orbitfold — APPROVED** [review]
Looks good to me.

**Comment by orbitfold** [comment]
oh you will need to change test_mc_analysis.py, the [0] indexing just needs to be removed i think. since this changes how results are returned?

**Comment by wedeling** [comment]
It shouldn't matter I think. I'll have a look

**Comment by orbitfold** [comment]
```
>       assert(s1_conf['x1']['low'] == pytest.approx(0.14387035, 0.01))
E       assert 0.19341946180114922 == 0.14387035 ± 1.4e-03
E        +  where 0.14387035 ± 1.4e-03 = <function approx at 0x7f12acd2fa60>(0.14387035, 0.01)
E        +    where <function approx at 0x7f12acd2fa60> = pytest.approx
```

Is there some deeper issue here or just because of the changed order of the calls to the random number generator?

**Review by jlakhlili — APPROVED** [review]

**Comment by DavidPCoster** [comment]
@wedeling -- should this be fixed and merged?  Or discarded?  Work on this started more than 3 years ago ...

**Comment by wedeling** [comment]
@DavidPCoster Not sure, it's got quite some work in it, but's it's been 3 years, there might be conflicts with the current version.  Also, the HDF5 collator probably deserves it's own PR.

**Comment by wedeling** [comment]
Ill will add these changes in the hackathon2024 repo

**Pull request closed without merging**
