### PR TITLE
QMC: change n_samples

### PR DESCRIPTION
**Pull request by jlakhlili**
use: `n_samples = (d + 2) * n_mc_samples.`

### CODE REVIEW

**Comment by orbitfold** [comment]
You will need to change the tests as well

**Comment by jlakhlili** [comment]
Which tests?!!!!! This change is inside the Sampler and it not affect any tests.

**Comment by orbitfold** [comment]
> Which tests?!!!!! This change is inside the Sampler and it not affect any tests.

The ones that are failing because of the changes.

**Comment by jlakhlili** [comment]
Changer are in made PR #271

**Pull request closed without merging**
