### PR TITLE
implementing new simplex stochastic collocation sampler

### PR DESCRIPTION
**Pull request by wedeling**
This came out of the last SEAVEA hackathon,  the simplex stochastic collocation (SSC) method to handle QoI with discontinuities or other related irregularities (e.g. high gradients)

@orbitfold @djgroen  I got an error with flake8: `ImportError: cannot import name 'python_3000_backticks' from 'pycodestyle'`. This happened when the automatic tests are run. Cannot quite figure this out. I have turned off the flake8 test in `python-package.yml` for now.

I have added:

* a new sampler: `easyvvuq/sampling/simplex_stochastic_collocation.py`
* a corresponding analysis class: `easyvvuq/analysis/SSCAnalysis.py`
* `tests/test_SSC.py`: a test for the sampler and analysis classes
* `tutorial/simplex_stochastic_collocation_tutorial.ipynb`: a tutorial on the use of the method, as well as some theory behind it, and an example of the failure of standard SC for discontinuous QoI. I could be good if someone presses play on it to see if it runs without issue.

What is missing

* the ability to handle vector QoI.
* the ability to scale to high-dimensional problems.

These can be resolved, but will take some time. I plan to do this early 2023. For now it is useful for discontinuous scalar QoI with at most 5 inputs or so.

### CODE REVIEW

**Comment by djgroen** [comment]
This PR looks good to me, so I'm happy to approve it. The missing features can be added later on :).

**Review by djgroen — APPROVED** [review]
This all looks good to me.

**Comment by djgroen** [comment]
@wedeling In regards to flake8, could it be that we need to update the version to 6.0+ to get rid of this error?

That is what I seem to conclude from this page...
https://stackoverflow.com/questions/74630287/failedtoloadplugin-python-3000-backticks-when-running-flake8-after-upgrading-fla

**Comment by djgroen** [comment]
Anyway, it's merged already, but thought this page could help...?

**Comment by wedeling** [comment]
> @wedeling In regards to flake8, could it be that we need to update the version to 6.0+ to get rid of this error?
> 
> That is what I seem to conclude from this page... https://stackoverflow.com/questions/74630287/failedtoloadplugin-python-3000-backticks-when-running-flake8-after-upgrading-fla

Yes, I saw that too. One of the comments reads ```@NicolasMartinez I maintain flake8, that import is only present in the 5.x version.``` So I think it's actually caused by an old version of flake8?

**Pull request merged**
