### PR TITLE
Switch packaging to `pyproject.toml`

### LINKED ISSUE #420: move from setup.py to pyproject.toml
It is probably time to move from setup.py to pyproject.toml

```
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!

```

### PR DESCRIPTION
**Pull request by ZedThree**
Also requires switching auto-versioning to `setuptools_scm` from `versioneer`, as the latter doesn't work with `pyproject.toml`-only packages

Closes #420

### CODE REVIEW

**Comment by ZedThree** [comment]
Benchmark is failing because the PR is from a fork and so doesn't have push permissions

**Comment by ZedThree** [comment]
This will also fix the docs not building most of the API: https://easyvvuq.readthedocs.io/en/dev/py-modindex.html

**Comment by ZedThree** [comment]
This would be pretty trivial to get working with numpy 2.0 as well, the only changes required are:

- replace four instances of `np.in1d` with `np.isin`
- loosen the pinned `chaospy` and `numpoly` versions

Would you like those changes in this PR or a separate one?

**Review by DavidPCoster — APPROVED** [review]
I'm not an expert on TOML but this looks OK to me

**Comment by djgroen** [comment]
There's an autopush task failing for some reason. I'll try to rerun the tests.

**Comment by djgroen** [comment]
Ok, I'm inclined to approve and merge this in and then look into the benchmark build issue if it still exists. Because it's a token error, I suspect this could be a spurious problem?

**Review by djgroen — APPROVED** [review]
Looks generally okay to me. pyproject.toml may need updating, but since the build and tests pass there are no obvious dependency issues at the moment.

**Pull request merged**
