### PR TITLE
Goghino dev

### PR DESCRIPTION
**Pull request by djgroen**

### CODE REVIEW

**Comment by djgroen** [comment]
Hi Juraj. / @goghino 

I've made a new pull request with the branch on the main server, so that we can all help to make it work correctly. I've also included some of the fixed we had on the main branch.

I tried testing it, and fixed a few small things already. However, there is one PCE test that now crashes that used to work before. Since you have modified the PCE implementation in this pull request, could you perhaps look into this and see if you can figure out how to fix it?

See: https://github.com/UCL-CCS/EasyVVUQ/pull/400/files#diff-4cc0198f836e5bcb243d6fe18e309f0893e45ed9bd653d58ab868e1a84637e91

Cheers,
-Derek

**Comment by goghino** [comment]
Hi Derek,

thanks for letting me know. I have noticed the failure of the following test, I think it is the one you are referring to:
`FAILED tests/test_vector.py::test_gauss_vector_pce - TypeError: len() of unsized object`
It is now resolved and the test passes successfully.

Please let me know if I can do anything else.

Best,
Juraj

**Comment by djgroen** [comment]
Hi Juraj / @goghino . Well well. It seems like that fix resolved a whole lot of testing issues. I'm waiting for the last checks, but it looks like we may be merging this in after all :+1: .

**Comment by djgroen** [comment]
Two of the checks haven't been performed yet, and I am not sure how to trigger them? All the others seem to work though, so I think this PR is ready for review?

**Review by DavidPCoster — APPROVED** [review]
Didn't see any obvious problems ...

**Pull request merged**
