### PR TITLE
QCG-PJ improvements

### PR DESCRIPTION
**Pull request by bartoszbosak**
Modified way of passing arguments to QCG-PJ tasks.

### CODE REVIEW

**Review by DavidPCoster — APPROVED** [review]

**Comment by orbitfold** [comment]
Is this ready for merging or is there work to be done?

**Comment by bartoszbosak** [comment]
> 

I do not expect changes, but since it is not very urgent I think we can wait a week. Our aim is to have it merged for the M42 VECMA release.

**Comment by bartoszbosak** [comment]
> Is this ready for merging or is there work to be done?

I've not provided more updates, so I think it is ready to merge in a current form. @orbitfold, could you please push it forward?

**Comment by orbitfold** [comment]
I've left some comments. Once fixed I will merge.

**Comment by bartoszbosak** [comment]
I've cleaned some residue after the debug in `easyvvuq/actions/execute_local.py` file. Is it ok now, or you think that there is still something left that I should fix ?

**Pull request merged**
