### PR TITLE
Remove the no longer needed distributions/ dir. In any case, these di…

### PR DESCRIPTION
**Pull request by raar1**
…sts would not be compatible with newer easyvvuq versions.

I don't believe anyone is using this for anything anymore. CP provides all dists now.

### CODE REVIEW

**Comment by jlakhlili** [comment]
@raar1 I added in my branch  two-piece normal distribution https://en.wikipedia.org/wiki/Split_normal_distribution

**Comment by raar1** [comment]
@jlakhlili Ah, no, that's fine! I'll modify this PR then. Wanted to check if anyone was still using this. I assume I can still get rid of the "options" and "custom_histogram" ones, right?

Adding that to chaospy would seem like a good contribution though.

**Comment by jlakhlili** [comment]
Now it's time to add histogram with this new distribution in chaospy.

**Comment by jlakhlili** [comment]
I moved the dist to fusion git before to ask chaospy guys. So,  you can delete the distribution module from there.

**Comment by raar1** [comment]
Ah ok, thanks. I was just trying to tidy up, and maybe it's best to just not have a distributions module at all. Doesn't stop us providing a way to write custom distributions in future perhaps, although it's maybe better to delegate this aspect to chaospy.

**Pull request merged**
